name: resify
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  
  # Dependency ditaruh sejajar dengan flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # flutter_launcher_icons adalah alat bantu dev, jadi ditaruh di sini
  flutter_launcher_icons: ^0.13.1

# --- KONFIGURASI UTAMA ---

# 1. Konfigurasi Launcher Icon (Harus di paling kiri/Root level)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/resify_logo.png" 
  min_sdk_android: 21

# 2. Konfigurasi Flutter & Assets
flutter:
  uses-material-design: true

  # Pastikan path ini sesuai dengan folder Anda.
  # SANGAT DISARANKAN: Pindahkan folder assets agar sejajar dengan lib (di root), 
  # bukan di dalam lib. Jadi path-nya menjadi:
  assets:
    - lib/assets/images/resify_logo.png
    - lib/assets/images/icon_resistor.png
    - lib/assets/images/icon_kalkulator.png