name: resify
description: "Aplikasi Kalkulator Teknik Resistor & Ohm"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- DEPENDENCIES (PUSTAKA) ---
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0    # Biar font aplikasi bagus
  sqflite: ^2.3.0         # Database Lokal (Wajib buat fitur History)
  path: ^1.8.3            # Helper buat nyari lokasi database
  intl: ^0.18.1           # Format Tanggal (Wajib buat fitur History)
  # -----------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Alat pembuat icon aplikasi (Settingan kamu sebelumnya)
  flutter_launcher_icons: ^0.13.1

# --- KONFIGURASI ICON APLIKASI ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # Pastikan file resify_logo.png ada di folder ini
  image_path: "lib/assets/images/resify_logo.png"
  min_sdk_android: 21

# --- KONFIGURASI FLUTTER & ASET ---
flutter:
  uses-material-design: true

  # Daftarkan folder aset gambar di sini
  assets:
    - lib/assets/images/